server:
  port: 9527
spring:
  application:
    name: zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul-9527
    prefer-ip-address: true
zuul:
  routes:
    mydept.serviceId: springcloud-dept
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /zhang