#server.port=80
#eureka.client.service-url.defaultZone=http://localhost:7001/eureka
#eureka.instance.instance-id=deptconsumer-80
#eureka.instance.prefer-ip-address=true
#
#spring.application.name=deptconsumer-80
#info.app.name=deptconsumer80
#info.company.name=www.zhang.com
#info.build.artifactId=$project.artifactId$
#info.build.version=$project.version$
#management.endpoints.web.exposure.include=*
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false
feign:
  hystrix:
    enabled: true