
server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #集群版本，经过域名映射后的主机名
  #    hostname: localhost #eureka服务端的实例名称 单机版本的时候使用
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
#      集群，与其它server同步
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
#  server:
#    # 开发环境设为false，关闭自我保护机制，服务器不推荐使用
#    enable-self-preservation: false
#    # 清理间隔（单位毫秒，默认是60*1000）
#    eviction-interval-timer-in-ms: 4000
spring:
  application:
    name: server-eureka-7001
